# ----------------------------------------------------------------------------
#
# Package             : dask
# Source Repo         : https://github.com/dask/dask
# Travis Job Link     : https://travis-ci.com/github/asellappen/dask/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python

dist: focal 

matrix:
  include:
  #- env: PYTHON_VERSION="3.7"
  #- env: PYTHON_VERSION="3.8"
  #- env: PYTHON_VERSION="3.7"
  #  arch: ppc64le
  - env: PYTHON_VERSION="3.7"
    arch: ppc64le

sudo: required

before_install:
  #- sudo apt-get install gfortran libopenblas-dev liblapack-dev
  #- sudo apt-get install -y python-pygraphviz
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install python=$PYTHON_VERSION pip  pytest-xdist pytest
  - pip install pytest-parallel --no-cache-dir
  - pip install graphviz  --no-cache-dir
  - pip install python-coveralls --no-cache-dir
  - pip install cloudpickle --no-cache-dir
  - ip install "dask[dataframe]" --no-cache-dir
  - conda install llvmlite==0.36.0rc1  -c numba
  - python -m pip install numpy==1.20.1 --no-cache-dir
  - conda install  toolz  pandas multipledispatch jsonschema fsspec 

install:
  - python -m pip install --quiet --no-deps -e .

script: 
 #  -  python -m pytest -v dask --tests-per-worker 6
 #  -  py.test dask --runslow  --maxfail=2  --tests-per-worker 6
 #  -  py.test dask --runslow  --tests-per-worker 4
    -  py.test dask --runslow  -n4 
